### ISSUE TITLE
Jupyter notebook cartopy installation 

### ISSUE THREAD

**Issue by 7yl4r** [SchmidtDSE/afscgap#75]
Trying to run the Jupyter notebook from Ubuntu 22.04.2 LTS and I am seeing an error w/ Cartopy usage:

![image](https://github.com/SchmidtDSE/afscgap/assets/1051390/d35ac746-6db6-456c-a572-4f7ad3ea277d)

Steps taken to get here:
```
$ git checkout git@github.com:SchmidtDSE/afscgap.git
$ cd afscgap/notebooks
$ pip install -r requirements.txt
$ jupyter notebook
```

Looks like pip didn't fully set up what was needed?

**Comment by 7yl4r** [comment]
`sudo apt -y install libgeos-dev` (as suggested in [cartopy install docs](https://scitools.org.uk/cartopy/docs/latest/installing.html#ubuntu-debian) does not fix.

**Comment by sampottinger** [comment]
Thanks @7yl4r! Unfortunately this is working for me on PopOS. That said, [our binder](https://mybinder.org/v2/gh/SchmidtDSE/afscgap/main?urlpath=/tree/index.ipynb) is actually a Docker container which uses `ubuntu:jammy-20230301` as its base. I just re-ran that in Docker and Cartopy appears to work there. You can see the docker file at https://github.com/SchmidtDSE/afscgap/blob/main/Dockerfile. Can you see if that Docker container works for you? Here is how I ran it...

```
$ git checkout git@github.com:SchmidtDSE/afscgap.git
$ cd afscgap
$ docker build --no-cache -t afscgap-notebooks .
$ docker run -it --rm -p 8888:8888 afscgap-notebooks jupyter notebook --ip=0.0.0.0 --port=8888
```

So, it does appear to work for me under a "fresh" Ubuntu VM. Here's the equivalent of what the docker build does:

```
$ sudo apt-get update
$ sudo apt-get install -y python3-pip
$ sudo apt-get install -y python-is-python3
$ pip install --no-cache --upgrade pip
$ sudo apt-get -y install libgeos-dev
$ sudo pip install -r /requirements.txt
```

All that said, please let me know if there is anything else I can do to further assist. However, if the issue appears to be Cartopy related, I encourage you to reach out to that project directly in their [issues tracker](https://github.com/SciTools/cartopy/issues). Thanks!

**Comment by ocefpaf** [comment]
Wheels for cartopy have been a thorny issue for a while and building your own is not easy due to the geos+shapely dependencies conflicts. However, lots of progress have been made lately and looks like the next version of cartopy will use only shapely 2.0 and drop the direct dependency on geos. With that said, it is not a problem for `afscgap` to solve. Maybe just add some notes on the docs recommending a pre-built cartopy from a 3rd party packager until this situation improves.
